import numpy
x=numpy.array([[1,2],[3,4]])
y=numpy.array([[5,6],[7,8]])
print(numpy.add(x,y))
print(numpy.subtract(x,y))
print(numpy.multiply(x,y))
print(numpy.divide(x,y))
print(numpy.dot(x,y))
print(numpy.sqrt(x))
print(numpy.sum(x,axis=0))
print(y.T)
